from typing import Any, Optional


class LibraryController:
    def browse(self, uri: Any): ...
    def get_distinct(self, field: Any, query: Optional[Any] = ...): ...
    def get_images(self, uris: Any): ...
    def lookup(self, uris: Any): ...
    def refresh(self, uri: Optional[Any] = ...) -> None: ...
    def search(self, query: Any, uris: Optional[Any] = ..., exact: bool = ...): ...
