from typing import Any, Optional


class PlaybackController:
    def get_current_tl_track(self): ...
    def get_current_track(self): ...
    def get_current_tlid(self): ...
    def get_stream_title(self): ...
    def get_state(self): ...
    def set_state(self, new_state: Any) -> None: ...
    def get_time_position(self): ...
    def next(self) -> None: ...
    def pause(self) -> None: ...
    def play(self, tl_track: Optional[Any] = ..., tlid: Optional[Any] = ...) -> None: ...
    def previous(self) -> None: ...
    def resume(self) -> None: ...
    def seek(self, time_position: Any): ...
    def stop(self) -> None: ...
