from typing import Any, Optional


class PlaylistsController:
    def get_uri_schemes(self): ...
    def as_list(self): ...
    def get_items(self, uri: Any): ...
    def create(self, name: Any, uri_scheme: Optional[Any] = ...): ...
    def delete(self, uri: Any): ...
    def lookup(self, uri: Any): ...
    def refresh(self, uri_scheme: Optional[Any] = ...) -> None: ...
    def save(self, playlist: Any): ...
