from typing import Any, Optional


class TracklistController:
    def get_tl_tracks(self): ...
    def get_tracks(self): ...
    def get_length(self): ...
    def get_version(self): ...
    def get_consume(self): ...
    def set_consume(self, value: Any) -> None: ...
    def get_random(self): ...
    def set_random(self, value: Any) -> None: ...
    def get_repeat(self): ...
    def set_repeat(self, value: Any) -> None: ...
    def get_single(self): ...
    def set_single(self, value: Any) -> None: ...
    def index(self, tl_track: Optional[Any] = ..., tlid: Optional[Any] = ...): ...
    def get_eot_tlid(self): ...
    def eot_track(self, tl_track: Any): ...
    def get_next_tlid(self): ...
    def next_track(self, tl_track: Any): ...
    def get_previous_tlid(self): ...
    def previous_track(self, tl_track: Any): ...
    def add(self, tracks: Optional[Any] = ..., at_position: Optional[Any] = ..., uris: Optional[Any] = ...): ...
    def clear(self) -> None: ...
    def filter(self, criteria: Any): ...
    def move(self, start: Any, end: Any, to_position: Any) -> None: ...
    def remove(self, criteria: Any): ...
    def shuffle(self, start: Optional[Any] = ..., end: Optional[Any] = ...) -> None: ...
    def slice(self, start: Any, end: Any): ...
